Repository InnoSWP/B21-02_Bibliogram, pull requests merged in 2022-06, with the labels that each got.

#23 Change AboutIU page
  .idea/B21-02_Bibliogram.iml
  .idea/misc.xml
  app.py
  static/css/about_info.css
  static/css/topnav.css
  templates/about_page.html
  templates/base.html
Labels: front-end

#26 Create a project information page
  app.py
  static/css/features_info.css
  static/images/1.jpg
  static/images/2.jpg
  static/images/3.jpg
  static/images/4.jpg
  static/images/arrowDown.jpg
  static/images/arrowUp.jpg
  templates/features_page.html
Labels: front-end

#35 Create a search page and authors page
  .idea/B21-02_Bibliogram.iml
  .idea/misc.xml
  app.py
  static/css/about_info.css
  static/css/features_info.css
  static/css/search_page.css
  static/css/topnav.css
  static/favicon.ico
  static/images/arrow_down.jpg
  static/images/arrow_up.jpg
  static/images/author_photoholder.jpg
  static/images/menu.png
  templates/author_page.html
  templates/base.html
  templates/publications_page.html
  templates/search_page.html
Labels: front-end

#36 Change a publications page
  app.py
  static/css/features_info.css
  templates/about_page.html
  templates/base.html
  templates/features_page.html
  templates/publications_page.html
Labels: front-end

#40 Allocate place for authors in a search page
  app.py
  static/css/search_page.css
  templates/search_page.html
Labels: front-end

#43 Complete all the database parts
  .idea/B21-02_Bibliogram.iml
  .idea/dataSources.xml
  .idea/misc.xml
  __pycache__/app.cpython-310.pyc
  __pycache__/data.cpython-310.pyc
  __pycache__/database_template.cpython-310.pyc
  app.py
  database_template.py
Labels: back-end

#45 Add new function to update system by user
  data.py
Labels: back-end

#48 fix: Rename functions
  data.py
  templates/author_publications.html
  templates/search_page.html
Labels: back-end, front-end

#46 Backend Develop: modify Publication Page, add correct data to Author Page
  __pycache__/data.cpython-310.pyc
  app.py
  data.py
  database_template.py
  templates/author_page.html
  templates/author_publications.html
  templates/co-author.html
  templates/search_page.html
Labels: back-end

#55 Update arrow leading to the top behaviour via script
  static/css/topnav.css
  templates/base.html
Labels: front-end

#65 Add wordcloud and graphic
  authors_4_0.json
  data.py
  static/css/topnav.css
  static/images/graphic.png
  static/images/wordcloud.png
  templates/base.html
Labels: front-end

#68 Change top panel on 5 pages
  .idea/B21-02_Bibliogram.iml
  .idea/misc.xml
  app.py
  static/css/co-author.css
  static/css/search_page.css
  static/images/background_main_page_panel.jpg
  templates/author_page.html
  templates/author_publications.html
  templates/co-author.html
  templates/publications_page.html
  templates/search_page.html
Labels: front-end

#69 Downoload the report
  __pycache__/data.cpython-310.pyc
  app.py
  data.py
  downloads/download.csv
  downloads/download.json
  downloads/download.tsv
  downloads/download.xlsx
  templates/author_publications.html
  templates/publications_page.html
Labels: back-end

#85 Add switches on publications page
  app.py
  static/css/search_page.css
  static/images/arrow_left.jpg
  static/images/arrow_right.jpg
  templates/base.html
  templates/publications_page.html
Labels: front-end

#87 Add order of sorting
  static/css/search_page.css
  templates/author_publications.html
  templates/publications_page.html
Labels: front-end

#90 Add switching of pages by number
  templates/publications_page.html
Labels: front-end

#94 Change color
  static/css/refresh_page.css
  templates/refresh_page.html
Labels: front-end

#95 Fix display of general statistics of authors
  templates/author_page.html
Labels: front-end

#97 Add graphic labels
  data.py
  static/images/graphic.png
Labels: back-end, front-end
